# Generated by Django 5.1.6 on 2025-03-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel')),
                ('internal_trips', models.ManyToManyField(blank=True, to='trips.internaltrip')),
                ('one_day_trips', models.ManyToManyField(blank=True, to='trips.onedaytrip')),
            ],
        ),
    ]
