# Generated by Django 5.1.6 on 2025-03-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0004_internaltripimage_onedaytripimage_delete_tripimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayTripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('travel_date', models.DateField()),
                ('departure_location', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.onedaytrip')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
