# Generated by Django 5.1.6 on 2025-03-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_onedaytripbooking_delete_booking'),
        ('hotels', '0003_alter_hotelimage_image'),
        ('trips', '0004_internaltripimage_onedaytripimage_delete_tripimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('room_type', models.CharField(choices=[('single', 'غرفة فردية'), ('double', 'غرفة مزدوجة'), ('suite', 'جناح')], max_length=10)),
                ('nights', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('departure_location', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('internal_trips', models.ManyToManyField(blank=True, to='trips.internaltrip')),
            ],
        ),
    ]
