# Generated by Django 5.1.6 on 2025-03-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_hotelbooking'),
        ('hotels', '0003_alter_hotelimage_image'),
        ('trips', '0004_internaltripimage_onedaytripimage_delete_tripimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_nights', models.IntegerField(default=3)),
                ('duration_days', models.IntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('trips', models.ManyToManyField(blank=True, to='trips.internaltrip')),
            ],
        ),
    ]
