# Generated by Django 5.1.6 on 2025-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=models.ImageField(upload_to='static/images/trips'),
        ),
    ]
