# Generated by Django 5.1.6 on 2025-03-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trips', '0002_alter_tripimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimage',
            name='one_day_trip',
        ),
        migrations.RemoveField(
            model_name='tripimage',
            name='trip',
        ),
        migrations.AddField(
            model_name='tripimage',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripimage',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=models.ImageField(upload_to='static/images/trips/'),
        ),
    ]
