# Generated by Django 5.1.6 on 2025-03-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_tripimage_one_day_trip_remove_tripimage_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/internal_trips/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.internaltrip')),
            ],
        ),
        migrations.CreateModel(
            name='OneDayTripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/one_day_trips/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.onedaytrip')),
            ],
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
